// Automatically generated by declarative-routing, do NOT edit
import { z } from "zod";

import { makePostRoute, makeRoute } from "./makeRoute";

const defaultInfo = {
    search: z.object({}),
};

import * as ApiChatRoute from "@/app/api/chat/route.info";
import * as ChatIdRoute from "@/app/chat/[id]/page.info";
import * as ChatRoute from "@/app/chat/page.info";
import * as HomeRoute from "@/app/page.info";

export const Home = makeRoute("/", {
    ...defaultInfo,
    ...HomeRoute.Route,
});
export const Chat = makeRoute("/chat", {
    ...defaultInfo,
    ...ChatRoute.Route,
});
export const ChatId = makeRoute("/chat/[id]", {
    ...defaultInfo,
    ...ChatIdRoute.Route,
});

export const postApiChat = makePostRoute(
    "/api/chat",
    {
        ...defaultInfo,
        ...ApiChatRoute.Route,
    },
    ApiChatRoute.POST,
);
